MODULE RetailSettings;

NAMESPACE Retail;

FORM options 'Settings';

DESIGN options {
    OBJECTS {
        NEW tabbedPane {
            type = TABBED;
            fill = 1;
            NEW commons {
                caption = 'Basic';
            }
        }
    }
} 

NAVIGATOR {
    NEW FOLDER retail 'Retail' WINDOW toolbar IMAGE 'retail.png' {
        NEW FOLDER operations 'Actions' {  
        }
        NEW FOLDER settings 'Customization' {
            NEW options;        
        }
    }
}