MODULE ProductLot;

REQUIRE Product, CategoryLot;

NAMESPACE MasterData;

dataUseLot 'Lot accounting' = DATA BOOLEAN (Product);
useLot 'Lot accounting' (Product i) = useLot() AND (dataUseLot(i) OR (useLot(category(i)) AND i IS Product)) MATERIALIZED;

EXTEND FORM item
    PROPERTIES (i) dataUseLot SHOWIF i IS Product AND useLot();
    
DESIGN item {
    tabs {
        inventory {
            MOVE PROPERTY(dataUseLot(i));
        }
    }
} 