MODULE BillInitial;

REQUIRE BillType;

NAMESPACE Invoicing;

loadDefaultData () + {
    NEW t = BillType {
        name(t) <- 'Purchase from an Vendor';
        id(t) <- 'wholesale';
        NEW n = Numerator {
            name(n) <- 'Purchase from an Vendor';
            series(n) <- 'PS';
            minValue(n) <- 1;
            maxValue(n) <- 999999;
            stringLength(n) <- 6;
            numerator(t) <- n;
        }
    }
}