MODULE ScrapPrint;

REQUIRE ScrapDone, DocTemplate;

NAMESPACE Inventory;

addressLocation 'Address' (Scrap s)  = linesAddress(location(s));

FORM printScrap 'Write-off of Products'
    OBJECTS o = Scrap PANEL 
    PROPERTIES(o) nameType, dateTime, nameLocation, addressLocation
    
    OBJECTS l = ScrapLine
    PROPERTIES(l) product, quantity
    FILTERS scrap(l) = o
;

@defineDocTemplate(scrap, 'magazines');
@defineDocTemplateForm(scrap, s);