MODULE PurchaseOrderInitial;

REQUIRE PurchaseOrderType;

NAMESPACE Purchase;

loadDefaultData () + {
    NEW t = OrderType {
        name(t) <- 'Purchase Order';
        id(t) <- 'vendor';

        NEW n = Numerator {
            name(n) <- 'Purchase Order';
            series(n) <- 'PO';
            minValue(n) <- 1;
            maxValue(n) <- 999999;
            stringLength(n) <- 6;
            numerator(t) <- n;
        }
    }
}