MODULE OutgoingPaymentPrint;

REQUIRE OutgoingPayment, DocTemplate;

NAMESPACE Invoicing;

FORM printOutgoingPayment 'Outgoing payment'

    OBJECTS o = OutgoingPayment PANEL 
    PROPERTIES(o)
        dateTime, number,
        namePartner, namePartnerAccount,
        nameCompany, nameCompanyAccount,
        amount, note, reference 
;

@defineDocTemplate(outgoingPayment, 'outgoing payment');
@defineDocTemplateForm(outgoingPayment, p);
