MODULE InvoiceInitial;

REQUIRE InvoiceType;

NAMESPACE Invoicing;

loadDefaultData () + {
    NEW t = InvoiceType {
        name(t) <- 'Invoice';
        id(t) <- 'wholesale';
        NEW n = Numerator {
            name(n) <- 'Invoice';
            series(n) <- 'IN';
            minValue(n) <- 1;
            maxValue(n) <- 999999;
            stringLength(n) <- 6;
            numerator(t) <- n;
        }
    }
    NEW t = InvoiceType {
        name(t) <- 'Retail';
        id(t) <- 'retail';
        taxIncluded(t) <- TRUE;
        NEW n = Numerator {
            name(n) <- 'Retail';
            series(n) <- 'Р2';
            minValue(n) <- 1;
            maxValue(n) <- 999999;
            stringLength(n) <- 6;
            numerator(t) <- n;
        }
    }
}