MODULE IncomingPaymentAnalyticAccount;

REQUIRE AnalyticAccount, IncomingPayment, IncomingPaymentType;

NAMESPACE Invoicing;

@definePaymentTypeAnalytic(incoming);

analyticAccount 'Cash flow teim' = DATA AnalyticAccount (IncomingPayment);
nameAnalyticAccount 'Cash flow teim' (IncomingPayment p) = name(analyticAccount(p));

EXTEND FORM incomingPayments PROPERTIES READONLY nameAnalyticAccount(p);

@definePaymentAnalytic(incoming);