MODULE IncomingPaymentPrint;

REQUIRE IncomingPayment, DocTemplate;

NAMESPACE Invoicing;

FORM printIncomingPayment 'Incoming payment'

    OBJECTS o = IncomingPayment PANEL 
    PROPERTIES(o)
        dateTime, number,
        namePartner, namePartnerAccount,
        nameCompany, nameCompanyAccount,
        amount, note, reference 
;

@defineDocTemplate(incomingPayment, 'incoming payment');
@defineDocTemplateForm(incomingPayment, p);