MODULE PurchaseOrderPrintInitialBs;

REQUIRE PurchaseOrderPrint, DocTemplate;

NAMESPACE Purchase;

loadDefaultData () + {
    NEW tm = OrderTemplate {
        name(tm) <- 'Purchase Order';
        template(tm) <- 'PurchaseOrderRu.jrxml';
        in(tm, OrderType t) <- TRUE;
    }
    NEW tm = OrderTemplate {
        name(tm) <- 'Request for a quote';
        template(tm) <- 'PurchaseQuoteRu.jrxml';
        in(tm, OrderType t) <- TRUE;
    }
}