MODULE OutgoingPaymentAnalyticAccount;

REQUIRE AnalyticAccount, OutgoingPayment, OutgoingPaymentType;

NAMESPACE Invoicing;

@definePaymentTypeAnalytic(outgoing);

analyticAccount 'Cash flow teim' = DATA AnalyticAccount (OutgoingPayment);
nameAnalyticAccount 'Cash flow teim' (OutgoingPayment p) = name(analyticAccount(p));

EXTEND FORM outgoingPayments PROPERTIES READONLY nameAnalyticAccount(p);

@definePaymentAnalytic(outgoing);
