MODULE ScrapInitial;

REQUIRE ScrapType;

NAMESPACE Inventory;

loadDefaultData () + {
    NEW r = ScrapType {
        name(r) <- 'Write-off of Products';

        NEW n = Numerator {
            name(n) <- 'Write-off of Products';
            series(n) <- 'WO';
            minValue(n) <- 1;
            maxValue(n) <- 999999;
            stringLength(n) <- 6;
            numerator(r) <- n;
        }
    }
}