MODULE InvoicingSettings;

NAMESPACE Invoicing;

FORM options 'Settings'
;

DESIGN options {
    OBJECTS {
        NEW tabbedPane {
            type = TABBED;
            fill = 1;
        }
    }
}

NAVIGATOR {
    NEW FOLDER invoicing 'Calculations' WINDOW toolbar IMAGE 'invoicing.png' {
        NEW FOLDER operations 'Actions' {
        }
        NEW FOLDER reporting 'Reports' { 
        }
        NEW FOLDER settings 'Customization' {
            NEW options;        
        }
    }
}
